### ISSUE TITLE
Multiple analog read

### ISSUE THREAD

**Issue by giacy86** [RobTillaart/AsyncAnalog#2]
Hi, i've noticed using your library that reading multiple analog pin return the same value.

**Comment by RobTillaart** [comment]
OK, and the question is?
I need more information to answer that question.

**Comment by RobTillaart** [comment]
As no issue appeared I close this issue

**Comment by giacy86** [comment]
Sorry for the delay, indidn't know that atmega328 has 1 adc multiplexed, so there aren't any issues.

**Comment by RobTillaart** [comment]
No problem, as it was silent for some time without a clear question I saw no reason to keep this issue open. 
If there are other problems, feel free to open a new issue.
